### ISSUE TITLE
Recuento de Borda

### ISSUE THREAD

**Issue by Moffinguer** [Moffinguer/decide-part-camaron-2#19]
## Expected Behavior
Debe de crearse la funcionalidad en base al [siguiente algoritmo](https://es.wikipedia.org/wiki/Cuenta_de_Borda)

## Actual Behavior
No está implementado

**Comment by adrrf** [comment]
está realizada la implementación del código del recuento, pero no está intergrada en el módulo de voting por falta de tiempo debido a un tiempo de espera superior al esperado en la integración con el otro equipo
