### ISSUE TITLE
Postprocesado para varias preguntas por votación

### ISSUE THREAD

**Issue by albdomrui20** [Moffinguer/decide-part-camaron-2#29]
### **Expected Behavior**
---
Debe cambiar de forma que teniendo varias preguntas por votación, se aplique un postprocesado a cada pregunta teniendo en cuenta el tipo de pregunta (nomal, pregunta si/no, etc).
### **Actual Behavior**
----

Actualmente el post procesado de la votación está hecho para una sola pregunta por votación

### **Natural workflow**
-----

1. Cambiar el postprocesado para que tenga en cuenta cada pregunta por votación

**Comment by albdomrui20** [comment]
no me permite etiquetar la issue
![Captura de pantalla 2023-11-27 155517](https://github.com/Moffinguer/decide-part-camaron-2/assets/72875238/aa3c409e-56fc-4858-94c1-ff9df1be7f59)

**Comment by Moffinguer** [comment]
Debido a las técnicas de postprocesado se prohibirá usar técnicas de postprocesado cuando no sean votaciones simples.
