### ISSUE TITLE
desactivar protección a develop

### ISSUE THREAD

**Issue by adrrf** [Moffinguer/decide-part-camaron-2#32]
## Expected Behavior
el workflow de pr automáticos deberia hacer pr cuando a develop se hace un push
## Actual Behavior
el workflow no funciona debido a la protección de las ramas
## Natural workflow

  1. desproteger la rama
  2. hacer re run al workflow

**Comment by Moffinguer** [comment]
Se ha eliminado la protección a la rama develop. 
Nos fuerza este cambio a hacer revisiones no automáticas del codigo por humanos, ya que sino, github prohibe hacer merges a ramas "protegidas"

**Comment by adrrf** [comment]
perfecto, hago re run al workflow
