### ISSUE TITLE
Bug in postprocIntegration

### ISSUE THREAD

**Issue by carlos-bermejo** [Moffinguer/decide-part-camaron-2#66]
## Expected Behavior
The store page is accessed correctly
## Actual Behavior
When you start the app and go to the store page, an error appears
## Natural workflow

  1. Go to store/urls.py
  2. Add app_name='store' in the file
  3. Check that the page and tests work

**Comment by adrrf** [comment]
se ha resuelto el bug en la rama de postproc. todo en orden
