### ISSUE TITLE
Método postprocesado incluye campo tipo

### ISSUE THREAD

**Issue by marolmmar1** [Moffinguer/decide-part-camaron-2#68]
## Expected Behavior
When obtaining the results of a vote, in the postproc atribute, the first argument of the json is called "type" and contains the name of the method used to process the data.
## Actual Behavior
Actually, as on decide part 3, this field only contains the same value of the "votes" atribute
## Natural workflow
intentionally blank

**Comment by dangalmar** [comment]
https://github.com/Moffinguer/decide-part-camaron-2/commit/140c43a63ec6424d56d8b358f99761bfb5a9180d
