### ISSUE TITLE
Integration with central

### ISSUE THREAD

**Issue by Moffinguer** [Moffinguer/decide-part-camaron-2#84]
## Expected Behavior
Merge all integration with other team with Central Repo

## Actual Behavior
It has older code from M2

## Natural workflow
Accept and merge changes on (this)[https://github.com/adrrf/decide-part-camaron/pull/9] PR

**Comment by dangalmar** [comment]
https://github.com/adrrf/decide-part-camaron/commit/db631a28dfd1b910d58b3a61cb2e805093b46b07
